### ISSUE TITLE
Unable to override DESTDIR

### ISSUE THREAD

**Issue by jramnani** [building5/ansible-vault-tools#3]
It looks like the Makefile is explicitly setting DESTDIR to be blank.
https://github.com/building5/ansible-vault-tools/blob/master/Makefile#L1

That means that I cannot override it during installation.

```
$ DESTDIR=/path/to/install make install
```

This makes it harder for a package maintainer to create a package for this.  I tried to create a Homebrew formula and couldn't, for example.

Perhaps what you wanted was a "shorthand variable" in Make?

> If you’d like a variable to be set to a value only if it’s not already set, then you can use the shorthand operator ‘?=’ instead of ‘=’.

https://www.gnu.org/software/make/manual/html_node/Setting.html#Setting

**Comment by leedm777** [comment]
Fixed in 2.0.1, although instead of `?=`, I followed [the GNU recommendations](https://www.gnu.org/prep/standards/html_node/DESTDIR.html) and just didn't set it at all. Seems odd to me, but I'll go on the assumption they know what they're doing.

Thanks for the interest! Ping me on the PR for the Homebrew formula. Would be neat to see.

FWIW, instead of overriding `DESTDIR`, I recommend a) overriding `prefix` and b) using [override variables](https://www.gnu.org/software/make/manual/html_node/Overriding.html) to do it. The `prefix` variable is more what you're looking for, and you should be able to set it to `#{prefix}` in your formula.

```
$ make install --dry-run prefix=/path/to/install
install -m 755 ansible-vault-merge.sh /path/to/install/bin/ansible-vault-merge
install -m 755 gpg-vault-password-file.sh /path/to/install/bin/gpg-vault-password-file
```

`DESTDIR` would be useful for deb or rpm packaging, where you want to do a staged install that gets packaged up.

**Comment by jramnani** [comment]
Thanks!  So, I tried submitting a formula to Homebrew for this but was rebuffed.  Alas, they have a minimum requirement of Github stars and watchers, which I didn't know about.  Until then I just have a local formula that I'm keeping up to date.

Thanks again for fixing this issue.  I appreciate it.

**Comment by leedm777** [comment]
@jramnani Thanks for your efforts, and I'm glad the scripts are helpful to you.

If you'd like to publish [your own Homebrew tap](https://github.com/Homebrew/brew/blob/master/docs/brew-tap.md), I'd gladly link to it from here.
